// Build-time: fetch custom SVG logos (for badges whose icon was removed from
// Simple Icons — AWS services, OpenAI), base64-encode them, and emit
// assets/js/logos.js as a { key: dataURI } map consumed by skills.js.
// Run: node scripts/build-logos.mjs
import { writeFileSync } from "node:fs";

// gilbarbara/logos sources (colorful, designed for dark surfaces)
const GB = "https://cdn.jsdelivr.net/gh/gilbarbara/logos/logos";
const SOURCES = {
  "aws":        { url:`${GB}/aws.svg` },
  "aws-ec2":    { url:`${GB}/aws-ec2.svg` },
  "aws-eks":    { url:`${GB}/aws-eks.svg` },
  "aws-ecs":    { url:`${GB}/aws-ecs.svg` },
  "aws-lambda": { url:`${GB}/aws-lambda.svg` },
  "aws-s3":     { url:`${GB}/aws-s3.svg` },
  "aws-sqs":    { url:`${GB}/aws-sqs.svg` },
  "aws-sns":    { url:`${GB}/aws-sns.svg` },
  "openai":     { url:`${GB}/openai-icon.svg`, recolorWhite:true },
};

// lakeFS has no published icon anywhere — hand-authored white "data versioning"
// glyph (a database cylinder with a branch node).
const LAKEFS = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><ellipse cx="9" cy="5" rx="6" ry="2.5"/><path d="M3 5v9c0 1.4 2.7 2.5 6 2.5"/><path d="M15 5v4"/><circle cx="18" cy="12" r="2.4" fill="#fff" stroke="none"/><circle cx="18" cy="19" r="2.4" fill="#fff" stroke="none"/><path d="M18 9v0M18 14.4V16.6"/></svg>`;

function toDataURI(svg){
  const b64 = Buffer.from(svg, "utf8").toString("base64");
  return `data:image/svg+xml;base64,${b64}`;
}

const out = {};
for(const [key, spec] of Object.entries(SOURCES)){
  const res = await fetch(spec.url);
  if(!res.ok){ console.error(`FAIL ${key}: ${res.status}`); process.exit(1); }
  let svg = await res.text();
  if(spec.recolorWhite){
    svg = svg.replace(/#000000/gi, "#FFFFFF").replace(/#000(?=["';\s])/gi, "#FFF");
  }
  out[key] = toDataURI(svg);
  console.log(`✓ ${key} (${svg.length}B)`);
}
out["lakefs"] = toDataURI(LAKEFS);
console.log("✓ lakefs (authored)");

const body = "// AUTO-GENERATED by scripts/build-logos.mjs — do not edit by hand.\n" +
  "export const LOGOS = " + JSON.stringify(out, null, 2) + ";\n";
writeFileSync(new URL("../assets/js/logos.js", import.meta.url), body);
console.log(`\nWrote assets/js/logos.js with ${Object.keys(out).length} logos.`);
